# Generated by Django 5.2.3 on 2025-07-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('msg', models.TextField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=5)),
                ('logo_photo', models.ImageField(upload_to='user_image/')),
                ('brand_post', models.TextField()),
            ],
        ),
    ]
